version: '3.8'

services:

  thingsboard:
    image: thingsboard/tb-postgres
    restart: always
    environment:
      - SERVICE_FQDN_THINGSBOARD_9090  # ← ESSENCIAL para o Coolify reconhecer como app web
      - TB_QUEUE_TYPE=in-memory
      - TB_DB_HOST=postgres
      - TB_DB_PORT=5432
      - TB_DB_NAME=thingsboard
      - TB_DB_USERNAME=postgres
      - TB_DB_PASSWORD=${POSTGRES_PASSWORD}
      - HTTP_BIND_PORT=9090
    depends_on:
      - postgres
    networks:
      - coolify  # ← ALTERADO
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thingsboard.rule=Host(`tb.smart-byte.dev`)"
      - "traefik.http.routers.thingsboard.entrypoints=https"  # ← ALTERADO
      - "traefik.http.routers.thingsboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.thingsboard.tls=true"
      - "traefik.http.services.thingsboard.loadbalancer.server.port=9090"

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=thingsboard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coolify  # ← ALTERADO

volumes:
  postgres_data:

networks:
  coolify:  # ← ALTERADO
    external: true
