version: '3.8'

services:
  thingsboard:
    image: thingsboard/tb-postgres:3.8.1
    restart: always
    environment:
      - TB_BASE_URL=https://tb.smart-byte.dev
      - TB_QUEUE_TYPE=kafka
      - TB_KAFKA_SERVERS=kafka:9092
      - TB_CACHE_REDIS_HOST=redis
      - TB_CACHE_REDIS_PORT=6379
      - LOAD_DEMO=false
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mc0w8owcw008s4ws4g8c4os4:5432/thingsboard?sslmode=require
      - SPRING_DATASOURCE_USERNAME=tb_admin
      - SPRING_DATASOURCE_PASSWORD=tb_admin
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_HIKARI_REGISTER_MBEANS=false
      - SPRING_JMX_ENABLED=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.thingsboard.server.dao.ThingsboardPostgreSQLDialect
      - HTTP_BIND_PORT=9090
      - MQTT_ENABLED=true
      - MQTT_BIND_PORT=1883
      - COAP_ENABLED=true
      - COAP_BIND_PORT=5683
      - LWM2M_ENABLED=true
      - LWM2M_BIND_PORT=5685
      - SNMP_ENABLED=true
      - SNMP_BIND_PORT=162
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - coolify
    cap_add:
      - NET_ADMIN
    volumes:
      - mytb_data:/data
      - mytb_logs:/var/log/thingsboard
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      # Web UI, API e healthcheck via Traefik (HTTPS)
      - "traefik.http.routers.thingsboard.rule=Host(`tb.smart-byte.dev`)"
      - "traefik.http.routers.thingsboard.entrypoints=https"
      - "traefik.http.routers.thingsboard.tls=true"
      - "traefik.http.routers.thingsboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.thingsboard.service=thingsboard"
      - "traefik.http.services.thingsboard.loadbalancer.server.port=9090"
      - "traefik.http.services.thingsboard.loadbalancer.healthcheck.path=/login"
      - "traefik.http.services.thingsboard.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.thingsboard.loadbalancer.healthcheck.timeout=5s"
      # MQTT TCP
      - "traefik.tcp.routers.tb-mqtt.entrypoints=mqtt"
      - "traefik.tcp.routers.tb-mqtt.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.tb-mqtt.service=tb-mqtt"
      - "traefik.tcp.services.tb-mqtt.loadbalancer.server.port=1883"
      # MQTT TLS (se ativar no futuro)
      - "traefik.tcp.routers.tb-mqtts.entrypoints=mqtt-secure"
      - "traefik.tcp.routers.tb-mqtts.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.tb-mqtts.tls=true"
      - "traefik.tcp.routers.tb-mqtts.service=tb-mqtts"
      - "traefik.tcp.services.tb-mqtts.loadbalancer.server.port=1883"
      # CoAP UDP
      - "traefik.udp.routers.tb-coap.entrypoints=coap"
      - "traefik.udp.routers.tb-coap.service=tb-coap"
      - "traefik.udp.services.tb-coap.loadbalancer.server.port=5683"
      # LwM2M UDP
      - "traefik.udp.routers.tb-lwm2m.entrypoints=lwm2m"
      - "traefik.udp.routers.tb-lwm2m.service=tb-lwm2m"
      - "traefik.udp.services.tb-lwm2m.loadbalancer.server.port=5685"
      # SNMP UDP
      - "traefik.udp.routers.tb-snmp.entrypoints=snmp"
      - "traefik.udp.routers.tb-snmp.service=tb-snmp"
      - "traefik.udp.services.tb-snmp.loadbalancer.server.port=162"
      # Segurança e rate limiting (opcional)
      - "traefik.http.routers.thingsboard.middlewares=security-headers"
      - "traefik.http.middlewares.security-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.rate-limit.ratelimit.average=100"
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://localhost:9090/login"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  zookeeper:
    image: bitnami/zookeeper:3.8
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:3.7.0
    restart: unless-stopped
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_MESSAGE_MAX_BYTES=10485760
      - KAFKA_CFG_MAX_REQUEST_SIZE=10485760
      - KAFKA_HEAP_OPTS=-Xmx1g -Xms1g
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - coolify

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass tb_admin
    volumes:
      - redis_data:/data
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  tb-js-executor:
    image: thingsboard/tb-js-executor:latest
    restart: always
    environment:
      - REMOTE_JS_EVAL_REQUEST_TOPIC=js.eval.requests
      - REMOTE_JS_EVAL_RESPONSE_TOPIC=js.eval.responses
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - LOGGER_LEVEL=info
      - LOG_FOLDER=logs
      - MAX_CPU_TIME=2000
      - MAX_ERRORS=3
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - coolify

volumes:
  zookeeper_data:
  kafka_data:
  redis_data:
  mytb_data:
    driver: local
  mytb_logs:
    driver: local

networks:
  coolify:
    external: true
